config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  resources :fogs do
    member do
      get "print"
    end
  end
  devise_scope :user do
    get 'logout', to: 'devise/sessions#destroy'
  end
  root :to => "fogs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fog.rb
class Fog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :validatable, :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|

      puts auth.inspect

      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email

      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def my_provider
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/fogs_controller.rb
class FogsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_fog, only: %i[ print show edit update destroy ]

  # GET /fogs or /fogs.json
  def index
    @fogs = Fog.all
  end

  # GET /fogs/1 or /fogs/1.json
  def show
  end

  # GET /fogs/1/print
  def print
    send_data(@fog.picture, type: 'image/png', disposition: 'inline')
  end

  # GET /fogs/new
  def new
    @fog = Fog.new
  end

  # GET /fogs/1/edit
  def edit
  end

  # POST /fogs or /fogs.json
  def create
    @fog = Fog.new(fog_params)
    respond_to do |format|
      if @fog.save
        CreatePictureJob.perform_later @fog
        format.html { redirect_to @fog, notice: "Fog was successfully created." }
        format.json { render :show, status: :created, location: @fog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fogs/1 or /fogs/1.json
  def update
    @fog.picture = nil
    respond_to do |format|
      if @fog.update(fog_params)
        CreatePictureJob.perform_later @fog
        format.html { redirect_to @fog, notice: "Fog was successfully updated." }
        format.json { render :show, status: :ok, location: @fog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fogs/1 or /fogs/1.json
  def destroy
    @fog.destroy
    respond_to do |format|
      format.html { redirect_to fogs_url, notice: "Fog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fog
      @fog = Fog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fog_params
      params.require(:fog).permit(:name, :words)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def base64_image image_data
    "<img src='data:image/png;base64,#{image_data}' />".html_safe
  end
  def flash_class(level)
    bootstrap_alert_class = {
      "success" => "alert-success",
      "error" => "alert-danger",
      "notice" => "alert-info",
      "alert" => "alert-danger",
      "warn" => "alert-warning"
    }
    bootstrap_alert_class[level]
  end
end

app/helpers/fogs_helper.rb
module FogsHelper
end

app/views/fogs/_form.html.erb
<%= form_with(model: fog, html: {:class => 'row g-3' }, local: true) do |form| %>
  <% if fog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fog.errors.count, "error") %> prohibited this fog from being saved:</h2>

      <ul>
        <% fog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-outline">
    <%= form.label :name, :class => 'form-label' %>
    <%= form.text_field :name, :class => 'form-control' %>
  </div>

  <div class="form-outline">
    <%= form.label :words, :class => 'form-label' %>
    <%= form.text_area :words, :class => 'form-control' %>
  </div>

  <div class="form-outline">
    <%= form.submit nil, :class => 'btn-primary', :style=>'color:#FFFFFF;' %>
  </div>
<% end %>

app/views/fogs/edit.html.erb
<div class="container mt-4 border">
  <div class="container-content">
    <h1 class="m-3">Editing Fog</h1>
    <div class="m-3">
      <%= render 'form', fog: @fog %>
      <%= link_to 'Show', @fog %> |
      <%= link_to 'Back', fogs_path %>
    </div>
  </div>
</div>

app/views/fogs/index.html.erb
<div class="container">
<%= render 'shared/message' %>
<h1>Fogs</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Words</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fogs.each do |fog| %>
      <tr>
        <td><%= fog.name %></td>
        <td><%= truncate fog.words, length: 30, separator: /\w+/ %></td>
        <td><%= link_to 'Show', fog %></td>
        <td><%= link_to 'Edit', edit_fog_path(fog) %></td>
        <td><%= link_to 'Destroy', fog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fog', new_fog_path %>

app/views/fogs/new.html.erb
<div class="container mt-4 border">
<%= render 'shared/message' %>
  <div class="container-content">
    <h1 class="m-3">New Fog</h1>
    <div class="m-3">
      <%= render 'form', fog: @fog %>
      <%= link_to 'Back', fogs_path %>
    </div>
  </div>
</div>

app/views/fogs/show.html.erb
<div class="container mt-4 border">
  <%= render 'shared/message' %>
  <div class="container-content">
    <h1 class="m-3">Show Fog</h1>
    <div class="m-3">
      <p>
        <strong>Name:</strong>
        <%= @fog.name %>
      </p>

      <p>
        <strong>Words:</strong>
        <%= truncate @fog.words, length: 30, separator: /\w+/ %>
      </p>

      <%= base64_image @fog.picture unless @fog.picture.nil? %>

      <br/><br/>

      <%= link_to 'Edit', edit_fog_path(@fog) %> |
      <%= link_to 'Back', fogs_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Wordfog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_message.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= flash_class(key) %> alert-dismissible fade show text-center" role="alert">
    <%= message %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"/>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="gradient-custom border">
  <ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="/">WordFog</a>
    </li>
    <% if current_user %>
    <li class="nav-item">
      <a class="nav-link active" href="/logout" tabindex="-1" aria-disabled="true">Logout</a>
    </li>
    <% end %>
  </ul>
</div>